baseURL = 'https://example.org/'
title = 'Buruh Hybrid | Tuah Hamid'
theme = 'hugo-coder'
markup.goldmark.renderer.unsafe = true
enableEmoji = true

[pagination]
pagerSize = 6

languagecode = "en"
defaultcontentlanguage = "en"

[markup.highlight]
style = "github-dark"

[params]
  author = "Tuah Hamid"
  info = "Buruh Hybrid"
  description = "Tuah Hamid is a Digital Engineer from Malaysia."
  keywords = "tuah, tuahhamid, buruh, buruhhybrid, website"
  avatarurl = "avatar.jpg"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "dark"
  hidecolorschemetoggle = false

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/tuahhamid"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/tuahhamid/"

[[params.social]]
  name = "email"
  icon = "fa-regular fa-comments fa-2x"
  weight = 3
  url = "mailto:tuah.edu@gmail.com"

# Menu links
[[menu.main]]
  name = "Posts"
  weight = 1
  url  = "posts"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about"